FROM golang:1.14.4
ENV GOPATH /go
ENV PATH $PATH:$GOPATH/bin

RUN mkdir -p /go/src/github.com/Tech-Design-Inc/vega
COPY . /go/src/github.com/Tech-Design-Inc/vega
WORKDIR /go/src/github.com/Tech-Design-Inc/vega
ENV PATH $PATH:/go/src/github.com/Tech-Design-Inc/cega
ENV GO111MODULE=on

RUN go mod tidy
RUN go get github.com/pilu/fresh

EXPOSE 8080
# CMD ["go", "run", "main.go"]
# CMD ["realize", "start", "--run"]
CMD ["fresh"]
